/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SelecaoMalhaController;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

import javax.swing.JRadioButton;

/**
 *
 * @author Pichau
 */
public class SelecaoMalha extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public SelecaoMalha() {
        initComponents();
    }
    
        public void adicionarAcaoBotaoConfirmar(ActionListener acao){
            buttonConfirm.addActionListener(acao);
        }
        
        public void adicionarAcaoRadioMalha1(ActionListener acao){
            radioMalha1.addActionListener(acao);
        }
        
        public void adicionarAcaoRadioMalha2(ActionListener acao){
            radioMalha2.addActionListener(acao);
        }
        
        public void adicionarAcaoRadioMalha3(ActionListener acao){
            radioMalha3.addActionListener(acao);
        }
        
        public JButton getBtnMalhaImagem(){
            return btnMalhaImagem;
        }
        
        public JRadioButton getRadioMalha1(){
            return radioMalha1;
        }

        public void exibirTela(){
            setVisible(true);
        }
        
         public void fecharTela(){
            setVisible(false);
        }
         
       
        public void redimensionarImagem(String imagePath) {
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        Image image = icon.getImage().getScaledInstance(btnMalhaImagem.getWidth(), btnMalhaImagem.getHeight(), Image.SCALE_SMOOTH);
        btnMalhaImagem.setIcon(new ImageIcon(image));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonConfirm = new javax.swing.JButton();
        radioMalha1 = new javax.swing.JRadioButton();
        radioMalha2 = new javax.swing.JRadioButton();
        radioMalha3 = new javax.swing.JRadioButton();
        btnMalhaImagem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonConfirm.setText("Confirmar");

        buttonGroup1.add(radioMalha1);
        radioMalha1.setText("Malha1");
        radioMalha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMalha1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMalha2);
        radioMalha2.setText("Malha2");
        radioMalha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMalha2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMalha3);
        radioMalha3.setText("Malha3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioMalha1)
                        .addGap(41, 41, 41)
                        .addComponent(radioMalha2)
                        .addGap(43, 43, 43)
                        .addComponent(radioMalha3)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMalhaImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(btnMalhaImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMalha1)
                    .addComponent(radioMalha2)
                    .addComponent(radioMalha3))
                .addGap(41, 41, 41)
                .addComponent(buttonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMalha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMalha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMalha1ActionPerformed

    private void radioMalha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMalha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMalha2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoMalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoMalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMalhaImagem;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton radioMalha1;
    private javax.swing.JRadioButton radioMalha2;
    private javax.swing.JRadioButton radioMalha3;
    // End of variables declaration//GEN-END:variables
}
